name: Update XML feed

on:
  schedule:
    - cron: "0 * * * *"   # každou hodinu
  workflow_dispatch:       # možnost spustit ručně

permissions:
  contents: write

jobs:
  update-xml:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: pip install requests

      - name: Run XML script
        run: python ./skript-xml-to-gh.py

      - name: Commit and push changes
        run: |
          git config --global user.name "github-actions"
          git config --global user.email "actions@github.com"
          git add gpcz_ntb.xml
          git commit -m "Automatická aktualizace feedu" || echo "No changes to commit"
          git pull --rebase --autostash origin main
          git push origin main
